feature: allow Request.GetBody to be set when gzipping
InfluxCommunity/influxdb3-go pull request #108
Opened 2024-10-04 13:36 UTC by taki-mekhalfa

Hello I am testing ``influxdb3`` to host my timeseries data. 

I am interacting with the DB using this library. I have one ``influxdb`` client shared among my ``go`` routines.  

I am regularely receiving errors of this kind when attempting to write data:

`http2: Transport: cannot retry err [http2: Transport received Server's graceful shutdown GOAWAY] after Request.Body was written; define Request.GetBody to avoid this error`

I noticed that the library does not allow for ``Request.Body`` to be set when gzipping is enabled. 

This change works around this to allow for more resilient client calls against influxdb3's HTTP/2 server.

2024-10-08 08:33 UTC, bednar requested changes
Hi @taki-mekhalfa,

Thank you for your Pull Request and for contributing to our project! 👍 We appreciate your effort and are looking forward to reviewing your changes.

Before we can proceed with a detailed review and accepting your PR, we need to ensure that all items on our Checklist are satisfied. Please take a look:

![image](https://github.com/user-attachments/assets/e3d76b8f-cf23-4a99-9fa6-d8b3d402f57a)

2024-10-08 12:17 UTC, alespour requested changes
Nice contribution, thanks! I only have two comments regarding error messages.

2024-10-08 12:17 UTC, alespour commented on influxdb3/write.go
> +			return nil, fmt.Errorf("unable to body gzip reader: %w", err)
I feel like error message should be reworded like eg
```suggestion
			return nil, fmt.Errorf("unable to compress body: %w", err)
```

2024-10-08 12:17 UTC, alespour commented on influxdb3/write.go
> +			return nil, fmt.Errorf("unable to compress write body: %w", err)
I feel like error message should be reworded like eg.

```suggestion
			return nil, fmt.Errorf("unable to read compressed body: %w", err)
```

2024-10-09 08:00 UTC, alespour approved these changes
LGTM

2024-10-09 13:25 UTC, bednar approved these changes
LGTM 🚀

2024-10-09 13:25 UTC, merged