[Draft] Support Type Guard
InfluxCommunity/influxdb3-go pull request #42
Opened 2023-09-25 23:00 UTC by arukiidou

Closes #

## Proposed Changes

_Briefly describe your proposed changes:_

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] Tests pass
- [ ] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

2023-09-26 08:41 UTC, bednar commented
@arukiidou, thank you for using our client and for your PR. We're excited to review it once it's ready.

2023-10-02 09:05 UTC, arukiidou commented
fixed,sorry🙏

2023-10-03 09:06 UTC, bednar requested changes

2023-10-03 09:06 UTC, bednar commented on influxdb3/value.go
> +// [Float] is IEEE-754 64-bit floating-point numbers. Default numerical type. InfluxDB supports scientific notation in float field values.
Add `Float` as a prefix to docs:

```suggestion
// Float [Float] is IEEE-754 64-bit floating-point numbers. Default numerical type. InfluxDB supports scientific notation in float field values.
```

2023-10-03 09:06 UTC, bednar commented on influxdb3/value.go
> +// [Integer] is signed 64-bit integers.
Add `Integer` as a prefix to docs:
```suggestion
// Integer [Integer] is signed 64-bit integers.
```

2023-10-03 09:06 UTC, bednar commented on influxdb3/value.go
> +// [UInteger] is unsigned 64-bit integers.
Add `UInteger` as a prefix to docs:

```suggestion
// UInteger [UInteger] is unsigned 64-bit integers.
```

2023-10-03 09:06 UTC, bednar commented on influxdb3/value.go
> +// [String] is plain text string. Length limit 64KB.
Add `String` as a prefix to docs:

```suggestion
// String [String] is plain text string. Length limit 64KB.
```

2023-10-03 09:06 UTC, bednar commented on influxdb3/value.go
> +// [Boolean] is true or false values.
Add `Boolean` as a prefix to docs:

```suggestion
// Boolean [Boolean] is true or false values.
```

2023-10-03 09:14 UTC, bednar commented
I have a question regarding the use of lineprotocol.Value. Is its usage necessary? What do you think about adding something like `AddStringField(k string, v string`) to Point?

```golang
func (m *Point) AddStringField(k string, v string) *Point {
	m.AddField(k, v)
	return m
}
```

2023-10-06 08:59 UTC, bednar commented
We aim to synchronize the API across our v3 clients — `js`, `go`, `java`, and `c#`. We've already updated the API in both the c# and js clients. For more information, see:

[JS Client PR #89](https://github.com/InfluxCommunity/influxdb3-js/pull/89)
[JS Client PR #89 File Diff](https://github.com/InfluxCommunity/influxdb3-js/pull/89/files#diff-c554c32407bd7f5cac83780c1cca6ee80e928747153298f2a50caed6c5c8f836)
[C# Client PR #52](https://github.com/InfluxCommunity/influxdb3-csharp/pull/52)
[C# Client PR #52 File Diff](https://github.com/InfluxCommunity/influxdb3-csharp/pull/52/files#diff-00f854f9fd585a20c2fee5e06f6b5e85ea4b7278f19f6e1165a9569edcea6b4c)

2023-10-18 10:25 UTC, arukiidou commented on influxdb3/value.go
> +// [Float] is IEEE-754 64-bit floating-point numbers. Default numerical type. InfluxDB supports scientific notation in float field values.
fixed.

2023-10-18 10:25 UTC, arukiidou commented on influxdb3/value.go
> +// [Integer] is signed 64-bit integers.
fixed.

2023-10-18 10:25 UTC, arukiidou commented on influxdb3/value.go
> +// [UInteger] is unsigned 64-bit integers.
fixed.

2023-10-18 10:26 UTC, arukiidou commented on influxdb3/value.go
> +// [String] is plain text string. Length limit 64KB.
fixed.

2023-10-18 10:26 UTC, arukiidou commented on influxdb3/value.go
> +// [Boolean] is true or false values.
fixed.

2023-10-18 11:44 UTC, bednar commented
@arukiidou thanks again for your PR. Can you please align your code with upcoming changes for `structured query` - https://github.com/InfluxCommunity/influxdb3-go/pull/45?

2023-10-18 12:48 UTC, arukiidou commented
> @arukiidou thanks again for your PR. Can you please align your code with upcoming changes for `structured query` - #45?

Yes, I will do so. It may take some time.

2023-10-29 13:49 UTC, arukiidou commented
@bednar 
- After a little consideration, I seem to be mostly satisfied with #45. I don't see anything to add, thanks!

2023-10-29 13:49 UTC, closed without merging